// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int network_interfaces_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int network_interfaces = 10;
	/// <summary>PID: 12 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int network_interfaces_discreetlist_12 = 12;
	/// <summary>PID: 12 | Type: read</summary>
	public const int network_interfaces_discreetlist = 12;
	/// <summary>PID: 20 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int multicastipaddress_20 = 20;
	/// <summary>PID: 20 | Type: read</summary>
	public const int multicastipaddress = 20;
	/// <summary>PID: 30 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int multicastipport_30 = 30;
	/// <summary>PID: 30 | Type: read</summary>
	public const int multicastipport = 30;
	/// <summary>PID: 40 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int timeout_in_seconds_40 = 40;
	/// <summary>PID: 40 | Type: read</summary>
	public const int timeout_in_seconds = 40;
	/// <summary>PID: 41 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int testduration_41 = 41;
	/// <summary>PID: 41 | Type: read</summary>
	public const int testduration = 41;
	/// <summary>PID: 51 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int status_51 = 51;
	/// <summary>PID: 51 | Type: read</summary>
	public const int status = 51;
	/// <summary>PID: 80 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int detailed_result_80 = 80;
	/// <summary>PID: 80 | Type: read</summary>
	public const int detailed_result = 80;
	/// <summary>PID: 83 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int deleted_row_83 = 83;
	/// <summary>PID: 83 | Type: read</summary>
	public const int deleted_row = 83;
	/// <summary>PID: 90 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int result_90 = 90;
	/// <summary>PID: 90 | Type: read</summary>
	public const int result = 90;
	public class Write
	{
		/// <summary>PID: 11 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int network_interfaces_11 = 11;
		/// <summary>PID: 11 | Type: write</summary>
		public const int network_interfaces = 11;
		/// <summary>PID: 48 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int clearAll_48 = 48;
		/// <summary>PID: 48 | Type: write</summary>
		public const int clearAll = 48;
		/// <summary>PID: 49 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int stopAnalyzing_49 = 49;
		/// <summary>PID: 49 | Type: write</summary>
		public const int stopAnalyzing = 49;
		/// <summary>PID: 50 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int startAnalyzing_50 = 50;
		/// <summary>PID: 50 | Type: write</summary>
		public const int startAnalyzing = 50;
		/// <summary>PID: 120 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int multicastipaddress_120 = 120;
		/// <summary>PID: 120 | Type: write</summary>
		public const int multicastipaddress = 120;
		/// <summary>PID: 130 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int multicastipport_130 = 130;
		/// <summary>PID: 130 | Type: write</summary>
		public const int multicastipport = 130;
		/// <summary>PID: 140 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int timeout_in_seconds_140 = 140;
		/// <summary>PID: 140 | Type: write</summary>
		public const int timeout_in_seconds = 140;
		/// <summary>PID: 141 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int testduration_141 = 141;
		/// <summary>PID: 141 | Type: write</summary>
		public const int testduration = 141;
	}
	public class Multicastanalyzertable
	{
		/// <summary>PID: 70</summary>
		public const int tablePid = 70;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 71</summary>
		public const int indexColumnPid = 71;
		public class Pid
		{
			/// <summary>PID: 71 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int multicastanalyzertable_index_71 = 71;
			/// <summary>PID: 71 | Type: read</summary>
			public const int multicastanalyzertable_index = 71;
			/// <summary>PID: 72 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int sourceip_72 = 72;
			/// <summary>PID: 72 | Type: read</summary>
			public const int sourceip = 72;
			/// <summary>PID: 73 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int sourceport_73 = 73;
			/// <summary>PID: 73 | Type: read</summary>
			public const int sourceport = 73;
			/// <summary>PID: 74 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int length_74 = 74;
			/// <summary>PID: 74 | Type: read</summary>
			public const int length = 74;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int multicastanalyzertable_index_71 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int multicastanalyzertable_index = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int sourceip_72 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int sourceip = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int sourceport_73 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int sourceport = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int length_74 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int length = 3;
		}
	}
}
public class WriteParameters
{
	/// <summary>PID: 11  | Type: write</summary>
	public System.Object Network_interfaces {get { return Protocol.GetParameter(11); }set { Protocol.SetParameter(11, value); }}
	/// <summary>PID: 48  | Type: write | DISCREETS: Clear All = 1</summary>
	public System.Object ClearAll {get { return Protocol.GetParameter(48); }set { Protocol.SetParameter(48, value); }}
	/// <summary>PID: 49  | Type: write | DISCREETS: Stop Analyzing = 1</summary>
	public System.Object StopAnalyzing {get { return Protocol.GetParameter(49); }set { Protocol.SetParameter(49, value); }}
	/// <summary>PID: 50  | Type: write | DISCREETS: Start Analyzing = 1</summary>
	public System.Object StartAnalyzing {get { return Protocol.GetParameter(50); }set { Protocol.SetParameter(50, value); }}
	/// <summary>PID: 120  | Type: write</summary>
	public System.Object Multicastipaddress {get { return Protocol.GetParameter(120); }set { Protocol.SetParameter(120, value); }}
	/// <summary>PID: 130  | Type: write</summary>
	public System.Object Multicastipport {get { return Protocol.GetParameter(130); }set { Protocol.SetParameter(130, value); }}
	/// <summary>PID: 140  | Type: write</summary>
	public System.Object Timeout_in_seconds {get { return Protocol.GetParameter(140); }set { Protocol.SetParameter(140, value); }}
	/// <summary>PID: 141  | Type: write</summary>
	public System.Object Testduration {get { return Protocol.GetParameter(141); }set { Protocol.SetParameter(141, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 70</summary>
	MulticastanalyzertableQActionTable multicastanalyzertable { get; set; }
	object Afterstartup_dummy { get; set; }
	object Title_begin_mutlicastoptions__fixed { get; set; }
	object Title_end_generic__fixed { get; set; }
	object Network_interfaces_10 { get; set; }
	object Network_interfaces { get; set; }
	object Network_interfaces_11 { get; set; }
	object Network_interfaces_discreetlist_12 { get; set; }
	object Network_interfaces_discreetlist { get; set; }
	object Multicastipaddress_20 { get; set; }
	object Multicastipaddress { get; set; }
	object Multicastipport_30 { get; set; }
	object Multicastipport { get; set; }
	object Timeout_in_seconds_40 { get; set; }
	object Timeout_in_seconds { get; set; }
	object Testduration_41 { get; set; }
	object Testduration { get; set; }
	object ClearAll_48 { get; set; }
	object ClearAll { get; set; }
	object StopAnalyzing_49 { get; set; }
	object StopAnalyzing { get; set; }
	object StartAnalyzing_50 { get; set; }
	object StartAnalyzing { get; set; }
	object Status_51 { get; set; }
	object Status { get; set; }
	object Multicastanalyzertable_index_71 { get; set; }
	object Multicastanalyzertable_index { get; set; }
	object Sourceip_72 { get; set; }
	object Sourceip { get; set; }
	object Sourceport_73 { get; set; }
	object Sourceport { get; set; }
	object Length_74 { get; set; }
	object Length { get; set; }
	object Detailed_result_80 { get; set; }
	object Detailed_result { get; set; }
	object Deleted_row_83 { get; set; }
	object Deleted_row { get; set; }
	object Result_90 { get; set; }
	object Result { get; set; }
	object Multicastipaddress_120 { get; set; }
	object Multicastipport_130 { get; set; }
	object Timeout_in_seconds_140 { get; set; }
	object Testduration_141 { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 70</summary>
	public MulticastanalyzertableQActionTable multicastanalyzertable { get; set; }
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 8  | Type: fixed</summary>
	public System.Object Title_begin_mutlicastoptions__fixed {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 9  | Type: fixed</summary>
	public System.Object Title_end_generic__fixed {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 10  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Network_interfaces_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Network_interfaces {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Network_interfaces_11 {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 12  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Network_interfaces_discreetlist_12 {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 12  | Type: read</summary>
	public System.Object Network_interfaces_discreetlist {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 20  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Multicastipaddress_20 {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 20  | Type: read</summary>
	public System.Object Multicastipaddress {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 30  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Multicastipport_30 {get { return GetParameter(30); }set { SetParameter(30, value); }}
	/// <summary>PID: 30  | Type: read</summary>
	public System.Object Multicastipport {get { return GetParameter(30); }set { SetParameter(30, value); }}
	/// <summary>PID: 40  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Timeout_in_seconds_40 {get { return GetParameter(40); }set { SetParameter(40, value); }}
	/// <summary>PID: 40  | Type: read</summary>
	public System.Object Timeout_in_seconds {get { return GetParameter(40); }set { SetParameter(40, value); }}
	/// <summary>PID: 41  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Testduration_41 {get { return GetParameter(41); }set { SetParameter(41, value); }}
	/// <summary>PID: 41  | Type: read</summary>
	public System.Object Testduration {get { return GetParameter(41); }set { SetParameter(41, value); }}
	/// <summary>PID: 48  | Type: write | DISCREETS: Clear All = 1</summary>
	public System.Object ClearAll_48 {get { return GetParameter(48); }set { SetParameter(48, value); }}
	/// <summary>PID: 48  | Type: write | DISCREETS: Clear All = 1</summary>
	public System.Object ClearAll {get { return Write.ClearAll; }set { Write.ClearAll = value; }}
	/// <summary>PID: 49  | Type: write | DISCREETS: Stop Analyzing = 1</summary>
	public System.Object StopAnalyzing_49 {get { return GetParameter(49); }set { SetParameter(49, value); }}
	/// <summary>PID: 49  | Type: write | DISCREETS: Stop Analyzing = 1</summary>
	public System.Object StopAnalyzing {get { return Write.StopAnalyzing; }set { Write.StopAnalyzing = value; }}
	/// <summary>PID: 50  | Type: write | DISCREETS: Start Analyzing = 1</summary>
	public System.Object StartAnalyzing_50 {get { return GetParameter(50); }set { SetParameter(50, value); }}
	/// <summary>PID: 50  | Type: write | DISCREETS: Start Analyzing = 1</summary>
	public System.Object StartAnalyzing {get { return Write.StartAnalyzing; }set { Write.StartAnalyzing = value; }}
	/// <summary>PID: 51  | Type: read | DISCREETS: Running = 1, Not Running = 2 | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Status_51 {get { return GetParameter(51); }set { SetParameter(51, value); }}
	/// <summary>PID: 51  | Type: read | DISCREETS: Running = 1, Not Running = 2 | EXCEPTIONS: N/A = -1</summary>
	public System.Object Status {get { return GetParameter(51); }set { SetParameter(51, value); }}
	/// <summary>PID: 71  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Multicastanalyzertable_index_71 {get { return GetParameter(71); }set { SetParameter(71, value); }}
	/// <summary>PID: 71  | Type: read</summary>
	public System.Object Multicastanalyzertable_index {get { return GetParameter(71); }set { SetParameter(71, value); }}
	/// <summary>PID: 72  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Sourceip_72 {get { return GetParameter(72); }set { SetParameter(72, value); }}
	/// <summary>PID: 72  | Type: read</summary>
	public System.Object Sourceip {get { return GetParameter(72); }set { SetParameter(72, value); }}
	/// <summary>PID: 73  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Sourceport_73 {get { return GetParameter(73); }set { SetParameter(73, value); }}
	/// <summary>PID: 73  | Type: read</summary>
	public System.Object Sourceport {get { return GetParameter(73); }set { SetParameter(73, value); }}
	/// <summary>PID: 74  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Length_74 {get { return GetParameter(74); }set { SetParameter(74, value); }}
	/// <summary>PID: 74  | Type: read</summary>
	public System.Object Length {get { return GetParameter(74); }set { SetParameter(74, value); }}
	/// <summary>PID: 80  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Detailed_result_80 {get { return GetParameter(80); }set { SetParameter(80, value); }}
	/// <summary>PID: 80  | Type: read</summary>
	public System.Object Detailed_result {get { return GetParameter(80); }set { SetParameter(80, value); }}
	/// <summary>PID: 83  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Deleted_row_83 {get { return GetParameter(83); }set { SetParameter(83, value); }}
	/// <summary>PID: 83  | Type: read</summary>
	public System.Object Deleted_row {get { return GetParameter(83); }set { SetParameter(83, value); }}
	/// <summary>PID: 90  | Type: read | DISCREETS: Finished = -3, Error = -2, No Packet Received = 0, Normal = 1, Multiple Source Address = 2, More than 2 Source Address = 3 | EXCEPTIONS: Off = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Result_90 {get { return GetParameter(90); }set { SetParameter(90, value); }}
	/// <summary>PID: 90  | Type: read | DISCREETS: Finished = -3, Error = -2, No Packet Received = 0, Normal = 1, Multiple Source Address = 2, More than 2 Source Address = 3 | EXCEPTIONS: Off = -1</summary>
	public System.Object Result {get { return GetParameter(90); }set { SetParameter(90, value); }}
	/// <summary>PID: 120  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Multicastipaddress_120 {get { return GetParameter(120); }set { SetParameter(120, value); }}
	/// <summary>PID: 130  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Multicastipport_130 {get { return GetParameter(130); }set { SetParameter(130, value); }}
	/// <summary>PID: 140  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Timeout_in_seconds_140 {get { return GetParameter(140); }set { SetParameter(140, value); }}
	/// <summary>PID: 141  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Testduration_141 {get { return GetParameter(141); }set { SetParameter(141, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		multicastanalyzertable = new MulticastanalyzertableQActionTable(this, 70, "multicastanalyzertable");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class MulticastanalyzertableQActionTable : QActionTable, IEnumerable<MulticastanalyzertableQActionRow>
{
	public MulticastanalyzertableQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<MulticastanalyzertableQActionRow> GetEnumerator() { return new QActionTableEnumerator<MulticastanalyzertableQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class MulticastanalyzertableQActionRow : QActionTableRow
{
	/// <summary>PID: 71 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Multicastanalyzertable_index_71 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 71 | Type: read</summary>
	public System.Object Multicastanalyzertable_index { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 72 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Sourceip_72 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 72 | Type: read</summary>
	public System.Object Sourceip { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 73 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Sourceport_73 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 73 | Type: read</summary>
	public System.Object Sourceport { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 74 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Length_74 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 74 | Type: read</summary>
	public System.Object Length { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	public MulticastanalyzertableQActionRow() : base(0, 4) { }
	public MulticastanalyzertableQActionRow(System.Object[] oRow) : base(0, 4, oRow) { }
	public static implicit operator MulticastanalyzertableQActionRow(System.Object[] source) { return new MulticastanalyzertableQActionRow(source); }
	public static implicit operator System.Object[](MulticastanalyzertableQActionRow source) { return source.ToObjectArray(); }
}
}
